services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant-large-display-card
    privileged: true
    restart: unless-stopped
    volumes:
      - ./config:/config
      - ./configuration.yaml:/config/configuration.yaml
      - ./dist:/config/www/large-display-card
    ports:
      - "8123:8123"
    environment:
      - TZ=Europe/London
